[Upload to S3] 과정에서 에러 발생
- $GITHUB_SHA 환경변수는 그대로 쓰면 되는데 앞에 env 를 붙여서 에러가 발생함
- 에러 메세지 내용
```
The user-provided path ./0e440829bb52e8a3f899f94c00e45c824e90344a.zip does not exist.
Error: Process completed with exit code 255.
```